version: "3.0"
volumes:
  mongodb-data: {}

services:
  webapp:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file: .env
    restart: always
    links:
      - db
  db:
    image: mongo:4.4
    container_name: mongo
    hostname: $MONGO_HOST
    env_file: .env
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27117:27017"
    restart: unless-stopped
